name: deploy-book

# Run this when there is a push to the main branch
on:
  push:
    branches:
    - main

# This job installs dependencies, build the book, and pushes it to `gh-pages`
jobs:
  deploy-book:
    permissions:
      id-token: write
      pages: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    # Install dependencies
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    # Build the book
    - name: Build the book
      run: |
        jupyter-book build Engineering-Materials-Programming-Book/
    
    # Upload the book's HTML as an artifact
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: "Engineering-Materials-Programming-Book/_build/html"

    # Deply the book's HTML to GitHub Pages
    - name: Deploy to GitHub Pages
      environment:
        name: github-pages
      id: depolyment
      uses: actions/deploy-pages@v2
